# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/landtoni-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter land santoni,$(TARGET_DEVICE)),)

endif
